#! /bin/sh

case "$1" in
   purge)
       rm -f /dev/cloop* || true
       ;;
   remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       ;;

   *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

#DEBHELPER#
